//ReactNextJS...
import Head from 'next/head'

//Components...
import dynamic from 'next/dynamic';
const StarrySky = dynamic(() => import('../components/StarrySky'), {
  loading: () => <p>Loading...</p>,
  ssr: true, // This can be set to true if you want SSR support for this component
});

//import About from './about';
const About = dynamic(() => import("./about"), {
  loading: () => <p>Loading...</p>,
  ssr: true, // This can be set to true if you want SSR support for this component
});

const MoreWork = dynamic(() => import("./moreWorks"), {
  loading: () => <p>Loading...</p>,
  ssr: true, // This can be set to true if you want SSR support for this component
});


import FloatingDownArrow from '@nextjsportfolio/components/FloatingDownArrow';

//React observer...
import { useInView } from 'react-intersection-observer';

//Styles...
import styles from '@nextjsportfolio/styles/Home.module.scss'

export default function Home() {

  const { ref, inView } = useInView({
    threshold: 0,
    triggerOnce: true,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="/favicon.ico" />


        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link 
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Ubuntu:wght@300;400;500;700&display=swap" 
          rel="stylesheet">
        </link>
      </Head>
      <main id={styles.main_section} className='main-font-family' >
        <div ref={ref} className={`${styles.container} ${inView ? styles.active : ""}`}>
          <div id={styles.text_box}>
            <div id={styles.pc_myname}>
              <h1>OSCAR REYES</h1>
              <div>Front-End-Developer</div>
            </div> 
          </div> 
          <FloatingDownArrow/>
          <StarrySky/> 
          <div className={styles.mountains}></div>
          <div className={styles.mountainstwo}></div>
          <div className={styles.foreground}></div>
        </div>
        <About/>
        <MoreWork/> 
      </main>
    </>
  )
}
