//ReactNextJS...
import Head from 'next/head'

//Components...
import dynamic from 'next/dynamic';

//import About from './about';
const About = dynamic(() => import("./about"), {
  loading: () => <p>Loading...</p>,
  ssr: true, // This can be set to true if you want SSR support for this component
});

import FloatingDownArrow from '@nextjsportfolio/components/FloatingDownArrow';

//React observer...
import { useInView } from 'react-intersection-observer';

//Styles...
import styles from '@nextjsportfolio/styles/Home.module.scss'

export default function Home() {


  const { ref, inView } = useInView({
    threshold: 0,
    triggerOnce: true,
  });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="/favicon.ico" />


        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link 
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Ubuntu:wght@300;400;500;700&display=swap" 
          rel="stylesheet">
        </link>
      </Head>
      <main id={styles.main_section} className='main-font-family' >

        <div ref={ref} className={`${styles.container} ${inView ? styles.active : ""}`}>
          <div id={styles.text_box}>
            <div id={styles.pc_myname}>
              <h1>OSCAR REYES</h1>
              <div>Front-End-Developer</div>
            </div> 
          </div> 
          
          <FloatingDownArrow/>


          <div className={styles.sky}>

            <div className={styles.main_containe}>
              <div className={styles.sub_container}>
                <div className={styles.sky}>
                  <div className={styles.stars}></div>
                  <div className={styles.stars2}></div>
                  <div className={styles.stars3}></div>
                  <div className={styles.comet}></div>
                </div>
              </div>
            </div>



            {/* <div className={styles.stars}></div>
            <div className={styles.stars}></div>
            <div className={styles.stars}></div>
            <div className={`${styles.star} ${styles.star1}`}></div>
            <div className={`${styles.star} ${styles.star2}`}></div>
            <div className={`${styles.star} ${styles.star3}`}></div>
            <div className={`${styles.star} ${styles.star4}`}></div>
            <div className={`${styles.star} ${styles.star5}`}></div> */}
          </div>
          <div className={styles.mountains}></div>
          <div className={styles.mountainstwo}></div>
          <div className={styles.foreground}></div>
        </div>

        <About/>

        
      </main>
    </>
  )
}
