//ReactNextJS...
import Head from 'next/head'
import React from 'react';
import Image from 'next/image';

//Components...
import FloatingDownArrow from '@nextjsportfolio/components/FloatingDownArrow';
import dynamic from 'next/dynamic';
const StarrySky = dynamic(() => import('../components/StarrySky'), {
    loading: () => <p>Loading...</p>,
    ssr: true, // This can be set to true if you want SSR support for this component
});
const About = dynamic(() => import("./about"), {
    loading: () => <p>Loading...</p>,
    ssr: true, // This can be set to true if you want SSR support for this component
});
const MoreWork = dynamic(() => import("./moreWorks"), {
    loading: () => <p>Loading...</p>,
    ssr: true, // This can be set to true if you want SSR support for this component
});
import ContactComponent from '@nextjsportfolio/components/ContactComponent';
import RougeAIChat from '@nextjsportfolio/components/RougeAIChat';

//Images...
import earth from '../../public/Frame 1.png'

//React observer...
import { useInView } from 'react-intersection-observer';

//React icons...
import { FaGithub, FaLinkedin } from 'react-icons/fa';

//Styles...
import styles from '@nextjsportfolio/styles/Home.module.scss'




export default function Home() {

  const { ref, inView } = useInView({
    threshold: 0,
    triggerOnce: true,
  });

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconSpace.png" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
        
        <link 
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&family=Ubuntu:wght@300;400;500;700&display=swap" 
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"/>

      </Head>
      <main id={styles.main_section} className='main-font-family'>
        <div 
          ref={ref} 
          className={`${styles.container} ${inView ? styles.active : ""}`}
        >
          <div id={styles.text_box}>
            <div className={styles.message}>
              <div className={styles.box}></div>
              <div>A MESSAGE FROM EARTH</div>
            </div> 
            <div 
              className={`bebas-neue-regular ${styles.main_msg}`}
            >
              GREETINGS MY FELLOW EARTHLINGS
            </div>
            <div className={styles.message}>
              <div>A MESSAGE FROM EARTH</div>
              <div className={styles.box}></div>
            </div> 
          </div> 

          <div className={`bebas-neue-regular ${styles.name}`}>
            I AM OSCAR
          </div>
          <FloatingDownArrow/>
          <StarrySky/>
          <div className={styles.socials}>
            <a href="https://github.com/lolster45">
              <FaGithub/>
            </a>
            <a href="https://www.linkedin.com/in/oscar-reyes-denova-34b4a81a2/" target='_blank'>
              <FaLinkedin/>
            </a>
          </div>

          <Image 
            className={styles.earth_pic} 
            src={earth} 
            alt="Earth" 
            layout="intrinsic"
          />          
          <div className={styles.mountains}></div>
          <div className={styles.mountainstwo}></div>
          <div className={styles.foreground}></div>
        </div>
        <About/>
        <RougeAIChat/>
        <MoreWork />
        <ContactComponent/>
      </main>
    </>
  )
}
